### ISSUE TITLE
Methods other than "GET" and "POST" are ignored

### ISSUE THREAD

**Issue by derekjobst** [patrick-steele-idem/meta-router#11]
When specifying methods that are not `GET` or `PUT` and not using the `ALL` option, the router will not recognize the route. 

### Example
If I where to specify the path:
```
[
    {
        "path": "/users/:user",
        "methods": ["DELETE", "PUT", "GET"],
        "handler": "require:./src/api/users/index"
    },
]
```

And then make a request `GET http://localhost:8080/users/123` the route will successfully be evaluated. However, `PUT http://localhost:8080/users/123` and `DELETE http://localhost:8080/users/123` will *not* work.

### Solution
I've isolated this issue to line 173 of [`lib/Route.js`](https://github.com/patrick-steele-idem/meta-router/blob/master/lib/Route.js#L173). The [`hasOwnProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) method is used on the `methods` Array to determine if a non GET/POST method is specified in the route definition. However, since this is an Array, `hasOwnProperty` will search over the keys, not the values. Thus, it will always return *false* in this case. Instead, an alternate way of searching the array should be used. I would propose checking if `indexOf` is greater than -1. 
#### Current
```javascript
170        if (this.isAll ||
171            (this.isGet && method === 'GET') ||
172            (this.isPost && method === 'POST') ||
173            this.methods.hasOwnProperty(method)) {
```
#### Fixed
```javascript
170        if (this.isAll ||
171            (this.isGet && method === 'GET') ||
172            (this.isPost && method === 'POST') ||
173            this.methods.indexOf(method) > -1) {
```

**Comment by derekjobst** [comment]
I would be happy to submit a PR to fix this @patrick-steele-idem

**Comment by viviangledhill** [comment]
Hi Derek, should be fine if you add the pull request - don't forget to add also a test case so that it's covered for the future. Thanks for your efforts!

**Comment by patrick-steele-idem** [comment]
Hi @derekjobst, thanks for reporting the problem. It looks like the bug is actually on the following line:

https://github.com/patrick-steele-idem/meta-router/blob/27df85e4fb1012e88e43363fb65c0ebb8e889d0a/lib/Route.js#L64

Incorrect:

```javascript
this.methods = methods;
```

Correct:

```javascript
this.methods = methodLookup;
```

I'll go ahead and add a failing test and then fix the problem. Thanks again.

**Comment by patrick-steele-idem** [comment]
New versions published:

- `meta-router@3.0.1`
- `meta-router@2.1.1`

Thanks, all, for your help.

**Comment by derekjobst** [comment]
Awesome. Thanks @patrick-steele-idem . Glad to help.
