### ISSUE TITLE
Proposal: allow route handler to export route metadata

### ISSUE THREAD

**Issue by patrick-steele-idem** [patrick-steele-idem/meta-router#7]
Instead of inlining route metadata with the route definition, it might be helpful for the handler to export additional route metadata so that the route metadata lives with the page handler. For example:

__Old:__

```javascript
[
    {
        "path": "GET /account",
        "handler": "require:./pages/account",
        "security": {
            "authenticationRequired": true,
            "redirect": true
        }
    }
]
```

_./pages/account.js:

```javascript
module.exports = function(req, res) {
    // ...
}
```

__New:__

```javascript
[
    {
        "path": "GET /account",
        "handler": "require:./pages/account"
    }
]
```

_./pages/account.js:

```javascript
exports.handler = function(req, res) {
    // ...
}

exports.routeMeta = {
    security: {
        authenticationRequired: true,
        redirect: true
    }
}
```

Thoughts? Concerns?

**Comment by bennettweb** [comment]
Just a thought - do you think we could push any further with the routes.json, so that it looks like:

```javascript
[
     "GET /account":  "require:./pages/account",
    //...
]
```

**Comment by fmsf** [comment]
I even would disagree with having the `require` is there any case where you are routing to something that is a js file?

``` 
[
     "GET /account":  "/pages/account#handler",
    //...
]
``` 

I don't think polluting the exports is the right way to do things. Although I agree it's nice to have them close by. How do you handle when a user wants to have multiple handles by controller?

I would suggest a `config.json` file or a `config.js` that lives next to the controller.

```
 {
   "handler" : {
        security: {
            authenticationRequired: true,
            redirect: true
        }
   }
```

**Comment by patrick-steele-idem** [comment]
Good suggestions. I'm going to throw out a few other options:

To avoid the awkward use case of having to loop over all of the properties to find the route, how about the following?:

```json
[
    "GET /account => ./pages/account#handler"
]
```

This would force the metadata to a separate place and for that we have two options:

___Option 1) Have the page handler module exports the route metadata___

_./pages/account/index.js_

```javascript
exports.handler = function(req, res) { ... }
exports.routeMetadata = { ... };
```

Alternatively:

```javascript
exports.handler = function(req, res) { ... };
exports.handler.routeMetadata = {
    security: {
        authenticationRequired: true,
        redirect: true
    }
};
```

___Option 2) Have the metadata be in a separate file next to the page handler module___

_./pages/account/route.json_

```json
{
    "security": {
        "authenticationRequired": true,
        "redirect": true
    }
}
```

Personally, my preference is to have the route handler export the metadata. Not being JSON and being JS allows more options and I don't think it really pollutes the page handler module to also export the metadata.

Thoughts?

**Comment by fmsf** [comment]
Attaching it to the handler function seems fine by me. Specially because it allows a user to do:

```
var standardMetadata = {
   security: { ... },
   localization: { ... }
}

exports.handler1.routeMetadata = standardMetadata;
exports.handler2.routeMetadata = standardMetadata;
```

Regarding
```
"GET /account => ./pages/account#handler"
```

It would be really cool if we could get a way to do reverse routing. I.e.: On a template
```
<a href="{route.pages.account.handler}></a>
````

That way we would only need to change routes in one file and it would propagate everywhere. We could probably populate this during dust pre render no?

**Comment by patrick-steele-idem** [comment]
Cool. I think we are getting close. All in favor of supporting a `routeMeta` (or `routeMetadata`?) property on the page handler?

Regarding the reverse router, that is something that we have discussed in the past and I think it would be nice to have. It gets a little complicated because some routes can have parameters. For example: `/account/:accountId`

The underlying Express route parser we are using doesn't make it easy to do reverse routing. Let's keep reverse routing as a separate issue (please feel free to open up another Github issue as a feature request). In the meantime, I recommend just maintaining a simple module of your own to do the URL generation for your app. For example:

```javascript
require('./url-util').getAccountPageUrl({accountId: '123'});
```

**Comment by skoranga** [comment]
any pattern on metadata sharing and cascading?
Also what you recommend for nested urls and url's with multiple actions?

```
[
    "GET /account => ./pages/account#handlerGet",
    "POST /account => ./pages/account#handlerPost",
    "GET /item => ./pages/item#handler",
    "GET /item/:itemId => ./pages/item#handlerItemId",
    "GET /item/:itemId/edit => ./pages/item#handlerItemIdEdit"
]
```

Is this correct way of expressing routes with the new spec? 
Also is there anyway I can have Error pages or status defined here?

**Comment by patrick-steele-idem** [comment]
Thanks for the feedback, @skoranga 

> any pattern on metadata sharing and cascading?

That can be done as @fmsf suggested:

```javascript
var standardMetadata = {
   security: { ... },
   localization: { ... }
}

exports.handler1.routeMetadata = standardMetadata;
exports.handler2.routeMetadata = standardMetadata;
```

> Also what you recommend for nested urls and url's with multiple actions?

I think keeping it simple and just repeating the pattern is probably okay. In theory, we could provide support for nesting routes, but I'm worried that will add unneeded complexity. Maybe we can revisit that as a separate feature request?

> Also is there anyway I can have Error pages or status defined here?

I think it is okay if the error handlers are registered outside the scope of meta-router.

Thanks again for the feedback.

**Comment by ramahadevan** [comment]
EmberJS has one of the best router concept , handles the routes flat / nested pretty neat, Why not look outside how things are solved and adapt ?

**Comment by patrick-steele-idem** [comment]
@ramahadevan Maybe it is because I haven't used Ember, but it is unclear to me how Ember router supports nested routes. Could you provide specific examples?

I was thinking of the following, but I think it is better to keep nested routes as a separate issue:

```json
[
    "GET /account => ./pages/account#handlerGet",
    "POST /account => ./pages/account#handlerPost",
    {
        "prefix": "/item",
        "routes": [
            "GET / => ./pages/item#handler",
            "GET /:itemId => ./pages/item#handlerItemId",
            "GET /:itemId/edit => ./pages/item#handlerItemIdEdit"
        ]
    }
]
```

**Comment by ramahadevan** [comment]
Sure , we can separate nesting separately, This pattern of Router is useful for lot of different reasons.

http://emberjs.com/guides/routing/defining-your-routes/#toc_nested-resources

  1.  I can construct urls from a route
  2.  I can nest the routes and do common logic around the parent etc

Sadly ember router in serverside havenot been implemented a lot

**Comment by bennettweb** [comment]
I'm not sure about the Ember way of doing things. In my opinion, this is overly complicated for what we're trying to achieve in the meta-router. I think that if we want to do nested stuff, then @patrick-steele-idem probably has the best solution.

Been away from this for a while, but I have to say, I like the way we're heading.

**Comment by fmsf** [comment]
@patrick-steele-idem Is there any update on how we can do this?

**Comment by patrick-steele-idem** [comment]
Thanks for the reminder @fmsf. I'll see if I can get this change in next week.

**Comment by patrick-steele-idem** [comment]
This proposal has been implemented a new version of this module has been published with the _minor_ version incremented: `meta-router@2.1.0` 

Please see the updated changelog: https://github.com/patrick-steele-idem/meta-router/blob/master/CHANGELOG.md#210

I think this change makes things a lot cleaner. Please let me know if you find any issues. Thanks @bennettweb, @fmsf, @skoranga, @ramahadevan and @dimichgh for the great discussion!
